title: IoT Academy
description: Trainings by Jakob Gabriel
baseurl: '/iot-academy'
url: 'https://jakobgabriel.github.io/iot-academy'
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
collections:
  courses:
    output: true
